###

POST http://localhost:8081/v1/auth/join
Accept: application/json
Content-type: application/json

{
  "email": "new-user",
  "password": ""
}

###

POST http://localhost:8081/v1/auth/join
Accept: application/json
Accept-Language: ru
Content-type: application/json

{
  "email": "new-user",
  "password": ""
}

###

POST http://localhost:8081/v1/auth/join
Accept: application/json
Accept-Language: ru_RU;q=0.9, ru;q=0.8, *;q=0,5
Content-type: application/json

{
  "email": "new-user",
  "password": ""
}